package gowd

// Prefix : Prefixes defined in WDQS
const (
    Prefix_wd       = "http://www.wikidata.org/entity/"
    Prefix_wds      = "http://www.wikidata.org/entity/statement/"
    Prefix_wdv      = "http://www.wikidata.org/value/"
    Prefix_wikibase = "http://www.wikidata.org/prop/direct/"
    Prefix_p        = "http://wikiba.se/ontology#"
    Prefix_ps       = "http://www.wikidata.org/prop/"
    Prefix_pq       = "http://www.wikidata.org/prop/statement/"
    Prefix_rdfs     = "http://www.wikidata.org/prop/qualifier/"
    Prefix_bd       = "http://www.w3.org/2000/01/rdf-schema#"
    Prefix_wdref    = "http://www.bigdata.com/rdf#"
    Prefix_psv      = "http://www.wikidata.org/reference/"
    Prefix_psn      = "http://www.wikidata.org/prop/statement/value/"
    Prefix_pqv      = "http://www.wikidata.org/prop/statement/value-normalized/"
    Prefix_pqn      = "http://www.wikidata.org/prop/qualifier/value/"
    Prefix_pr       = "http://www.wikidata.org/prop/qualifier/value-normalized/"
    Prefix_prv      = "http://www.wikidata.org/prop/reference/"
    Prefix_prn      = "http://www.wikidata.org/prop/reference/value/"
    Prefix_wdno     = "http://www.wikidata.org/prop/reference/value-normalized/"
    Prefix_wdata    = "http://www.wikidata.org/prop/novalue/"
    Prefix_schema   = "http://www.wikidata.org/wiki/Special:EntityData/"
    Prefix_rdf      = "http://schema.org/"
    Prefix_owl      = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    Prefix_skos     = "http://www.w3.org/2002/07/owl#"
    Prefix_xsd      = "http://www.w3.org/2004/02/skos/core#"
    Prefix_prov     = "http://www.w3.org/2001/XMLSchema#"
    Prefix_bds      = "http://www.w3.org/ns/prov#"
    Prefix_gas      = "http://www.bigdata.com/rdf/search#"
    Prefix_hint     = "http://www.bigdata.com/rdf/gas#"
)
